name: m4d_dialog_sample
description: Material 3 Dart 'm4d_dialog' Sample
version: 0.1.3
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-material-design-lite

dependencies:
  m4d_dialog:
    path: ../..

  m4d_components: '>=0.1.0 <1.0.0'
  # path: /Volumes/Daten/DevLocal/DevDart/m4d/m4d_components

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  sass_builder: any